name: Build AfriKoin (Staging)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Staging version (ex: 1.2.2-staging)'
        required: true
        default: '1.2.2-staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set version
        run: |
          sed -i "s/version: .*/version: ${{ github.event.inputs.version }}/" eas.json

      - name: Build APK (staging)
        run: eas build --platform android --profile preview --non-interactive
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: staging-apk
          path: ./build/*.apk
